# Copyright 2014 Tibor Benke

class syslog_ng (
  $config_file          = $::syslog_ng::params::config_file,
  $sbin_path            = '/usr/sbin',
  $purge_syslog_ng_conf = false,
  $user                 = 'root',
  $group                = 'root'
) inherits syslog_ng::params {

  validate_bool($purge_syslog_ng_conf)

  include syslog_ng::reload

  package { "$syslog_ng::params::package_name":
    ensure => present
  }

  $date = strftime("%Y-%m-%d")
  $time = strftime("%H:%M:%S:%L")

  concat { "$::syslog_ng::params::config_file":
    ensure => present,
    path   => $::syslog_ng::params::config_file,
    owner  => $user,
    group  => $group,
    warn   => true,
    ensure_newline => true,
    notify =>  Exec['syslog_ng_reload'],
    require => Package[$syslog_ng::params::package_name]
  }

  concat::fragment {'header':
    target => "$::syslog_ng::params::config_file",
    content => "# This file was generated by Puppet's ihrwein-syslog_ng module at #{time} on #{date}",
    order => '01'
  }
 
  service { "$syslog_ng::params::service_name":
    ensure  =>  running,
    require =>  Concat[$config_file]
  }
}
